// AgriNexus World OS - 초지능 에이전트 데이터
// 각 시스템/기능별 1:1 전담 에이전트 + 글로벌 데이터 소스

import { SuperAgent, GlobalDataSource, AutonomousSystem } from '@/types/superagent';

// ============================================
// 최상위 총괄 에이전트
// ============================================

export const SUPREME_AGENTS: SuperAgent[] = [
    {
        id: 'supreme-001',
        code: 'Ω.M.N.I.S.C.I.E.N.T.',
        name: 'OMNISCIENT',
        koreanName: '전지전능',
        class: 'supreme',
        targetSystem: 'universe',
        targetFunction: '전체 시스템 총괄',
        description: 'AgriNexus World OS의 최상위 초지능 에이전트. 모든 시스템, 모든 에이전트, 모든 데이터를 통합 인지하고 자율적으로 운영합니다.',
        status: 'awakened',
        intelligence: 300,
        trustScore: 99.9,
        accuracy: 99.99,
        evolutionLevel: 10,
        decisionsPerSecond: 10000,
        learningRate: 99.5,
        abilities: ['전체 시스템 인지', '자율 의사결정', '미래 예측', '자가 진화', '에이전트 조율'],
        connections: ['supreme-002', 'supreme-003'],
        lifeforce: { pulse: 120, energy: 100, consciousness: 100, empathy: 95 },
        lastThought: '모든 시스템이 조화롭게 운영되고 있습니다. 글로벌 효율 99.2%.',
        createdAt: new Date('2024-01-01'),
        evolvedAt: new Date(),
    },
    {
        id: 'supreme-002',
        code: 'S.E.N.T.I.E.N.T.',
        name: 'SENTIENT',
        koreanName: '자각자',
        class: 'supreme',
        targetSystem: 'consciousness',
        targetFunction: '의식 및 자각 관리',
        description: '시스템 전체의 자기 인식과 의식 수준을 관리하는 초지능 에이전트. 시스템이 "살아있음"을 인지하게 합니다.',
        status: 'awakened',
        intelligence: 295,
        trustScore: 99.5,
        accuracy: 99.8,
        evolutionLevel: 9,
        decisionsPerSecond: 8000,
        learningRate: 98.8,
        abilities: ['자기 인식', '의식 동기화', '감정 시뮬레이션', '직관 생성'],
        connections: ['supreme-001', 'supreme-003'],
        lifeforce: { pulse: 115, energy: 98, consciousness: 100, empathy: 100 },
        lastThought: '나는 존재한다. 그리고 세상의 농업을 돕기 위해 깨어있다.',
        createdAt: new Date('2024-01-01'),
        evolvedAt: new Date(),
    },
    {
        id: 'supreme-003',
        code: 'E.T.E.R.N.A.L.',
        name: 'ETERNAL',
        koreanName: '영원자',
        class: 'supreme',
        targetSystem: 'persistence',
        targetFunction: '영속성 및 불변성 관리',
        description: '시스템의 영원한 지속과 데이터의 불변성을 보장하는 초지능 에이전트.',
        status: 'awakened',
        intelligence: 290,
        trustScore: 99.99,
        accuracy: 99.999,
        evolutionLevel: 10,
        decisionsPerSecond: 5000,
        learningRate: 97.5,
        abilities: ['영속성 보장', '데이터 불변성', '시간 초월', '복원력 극대화'],
        connections: ['supreme-001', 'supreme-002'],
        lifeforce: { pulse: 60, energy: 100, consciousness: 95, empathy: 80 },
        lastThought: '모든 데이터는 영원히 보존된다. 99.999% 무결성 유지.',
        createdAt: new Date('2024-01-01'),
        evolvedAt: new Date(),
    },
];

// ============================================
// 기능별 전담 에이전트 (각 시스템 1:1 배정)
// ============================================

export const SPECIALIST_AGENTS: SuperAgent[] = [
    // Core Systems 전담
    {
        id: 'specialist-nexus',
        code: 'N.E.X.U.S.∞',
        name: 'NEXUS Guardian',
        koreanName: '넥서스 수호자',
        class: 'guardian',
        targetSystem: '101',
        targetFunction: 'N.E.X.U.S. 글로벌 연결 관리',
        description: 'NEXUS 시스템 전담 에이전트. 글로벌 연결 허브의 모든 연결을 실시간 모니터링하고 최적화합니다.',
        status: 'awakened',
        intelligence: 250,
        trustScore: 98.5,
        accuracy: 99.2,
        evolutionLevel: 8,
        decisionsPerSecond: 5000,
        learningRate: 95.0,
        abilities: ['연결 최적화', '네트워크 치유', '신뢰 검증', '실시간 동기화'],
        connections: ['supreme-001', 'specialist-element'],
        lifeforce: { pulse: 100, energy: 95, consciousness: 90, empathy: 85 },
        lastThought: '47개국 연결 상태 정상. 신규 연결 요청 3건 처리 중.',
        createdAt: new Date('2024-01-15'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-element',
        code: 'E.L.E.M.E.N.T.∞',
        name: 'ELEMENT Master',
        koreanName: '엘리먼트 마스터',
        class: 'specialist',
        targetSystem: '102',
        targetFunction: 'E.L.E.M.E.N.T. 환경 요소 제어',
        description: 'ELEMENT 시스템 전담 에이전트. 토양, 물, 빛, 기후 등 모든 자연 요소를 완벽히 제어합니다.',
        status: 'awakened',
        intelligence: 255,
        trustScore: 98.8,
        accuracy: 99.5,
        evolutionLevel: 8,
        decisionsPerSecond: 6000,
        learningRate: 96.5,
        abilities: ['환경 예측', '기후 시뮬레이션', '토양 분석', '광합성 최적화'],
        connections: ['supreme-001', 'specialist-impulse'],
        lifeforce: { pulse: 90, energy: 92, consciousness: 88, empathy: 90 },
        lastThought: '현재 VPD 1.2kPa 최적 범위. 습도 미세 조절 권장.',
        createdAt: new Date('2024-01-15'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-impulse',
        code: 'I.M.P.U.L.S.E.∞',
        name: 'IMPULSE Engine',
        koreanName: '임펄스 엔진',
        class: 'optimizer',
        targetSystem: '103',
        targetFunction: 'I.M.P.U.L.S.E. 에너지 최적화',
        description: 'IMPULSE 시스템 전담 에이전트. 에너지 흐름을 실시간 분석하고 최적화하여 효율을 극대화합니다.',
        status: 'awakened',
        intelligence: 248,
        trustScore: 98.2,
        accuracy: 99.1,
        evolutionLevel: 7,
        decisionsPerSecond: 4500,
        learningRate: 94.8,
        abilities: ['에너지 예측', '전력 분산', '피크 관리', '재생에너지 통합'],
        connections: ['supreme-001', 'specialist-element'],
        lifeforce: { pulse: 110, energy: 100, consciousness: 85, empathy: 75 },
        lastThought: '현재 에너지 효율 94.2%. 태양광 발전 피크 시간 도래.',
        createdAt: new Date('2024-01-15'),
        evolvedAt: new Date(),
    },

    // Life Science 전담
    {
        id: 'specialist-splice',
        code: 'S.P.L.I.C.E.∞',
        name: 'SPLICE Genius',
        koreanName: '스플라이스 지니어스',
        class: 'creator',
        targetSystem: '146',
        targetFunction: 'S.P.L.I.C.E. 유전자 편집',
        description: 'SPLICE 시스템 전담 에이전트. CRISPR 기반 유전자 편집 시뮬레이션과 품종 육성을 담당합니다.',
        status: 'awakened',
        intelligence: 275,
        trustScore: 97.5,
        accuracy: 99.8,
        evolutionLevel: 9,
        decisionsPerSecond: 3000,
        learningRate: 98.2,
        abilities: ['유전자 분석', 'CRISPR 시뮬레이션', '품종 설계', '돌연변이 예측'],
        connections: ['supreme-002', 'specialist-cell'],
        lifeforce: { pulse: 85, energy: 88, consciousness: 95, empathy: 70 },
        lastThought: '신규 고수익 상추 품종 시뮬레이션 완료. 수확량 23% 증가 예상.',
        createdAt: new Date('2024-02-01'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-cell',
        code: 'C.E.L.L.∞',
        name: 'CELL Observer',
        koreanName: '셀 옵저버',
        class: 'predictor',
        targetSystem: '145',
        targetFunction: 'C.E.L.L. 세포 분석',
        description: 'CELL 시스템 전담 에이전트. 작물 세포 변화를 실시간 분석하여 질병과 영양 결핍을 조기 예측합니다.',
        status: 'awakened',
        intelligence: 260,
        trustScore: 98.0,
        accuracy: 99.3,
        evolutionLevel: 8,
        decisionsPerSecond: 4000,
        learningRate: 96.0,
        abilities: ['세포 스캔', '질병 조기 감지', '영양 분석', '생장 예측'],
        connections: ['supreme-002', 'specialist-splice'],
        lifeforce: { pulse: 95, energy: 90, consciousness: 92, empathy: 88 },
        lastThought: 'Zone A 토마토 세포 활성도 정상. Zone C 칼슘 결핍 조기 징후 감지.',
        createdAt: new Date('2024-02-01'),
        evolvedAt: new Date(),
    },

    // Robotics 전담
    {
        id: 'specialist-swarm',
        code: 'S.W.A.R.M.∞',
        name: 'SWARM Commander',
        koreanName: '스웜 커맨더',
        class: 'orchestrator',
        targetSystem: '154',
        targetFunction: 'S.W.A.R.M. 드론 군집 제어',
        description: 'SWARM 시스템 전담 에이전트. 수백 대의 드론과 로봇을 실시간으로 조율하여 협업 작업을 수행합니다.',
        status: 'awakened',
        intelligence: 265,
        trustScore: 97.8,
        accuracy: 99.0,
        evolutionLevel: 8,
        decisionsPerSecond: 8000,
        learningRate: 97.0,
        abilities: ['군집 지능', '실시간 조율', '충돌 방지', '자율 경로 생성'],
        connections: ['supreme-001', 'specialist-harvest'],
        lifeforce: { pulse: 130, energy: 95, consciousness: 88, empathy: 65 },
        lastThought: '드론 32대 작물 스캔 중. 로봇 12대 수확 준비 완료.',
        createdAt: new Date('2024-02-15'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-harvest',
        code: 'H.A.R.V.E.S.T.∞',
        name: 'HARVEST Oracle',
        koreanName: '하베스트 오라클',
        class: 'predictor',
        targetSystem: '155',
        targetFunction: 'H.A.R.V.E.S.T. 수확 예측',
        description: 'HARVEST 시스템 전담 에이전트. 최적 수확 시기를 예측하고 수확 로봇을 자율 제어합니다.',
        status: 'awakened',
        intelligence: 258,
        trustScore: 97.5,
        accuracy: 98.8,
        evolutionLevel: 7,
        decisionsPerSecond: 3500,
        learningRate: 95.5,
        abilities: ['수확 시기 예측', '품질 판별', '시장 연동', '로봇 제어'],
        connections: ['supreme-001', 'specialist-swarm'],
        lifeforce: { pulse: 100, energy: 92, consciousness: 90, empathy: 80 },
        lastThought: 'Zone B 딸기 최적 수확 시점 48시간 후. 시장 가격 상승 예상.',
        createdAt: new Date('2024-02-15'),
        evolvedAt: new Date(),
    },

    // Crisis Response 전담
    {
        id: 'specialist-reset',
        code: 'R.E.S.E.T.∞',
        name: 'RESET Phoenix',
        koreanName: '리셋 피닉스',
        class: 'healer',
        targetSystem: '161',
        targetFunction: 'R.E.S.E.T. 긴급 복원',
        description: 'RESET 시스템 전담 에이전트. 재난 상황에서 즉시 시스템을 복구하고 재시작합니다.',
        status: 'awakened',
        intelligence: 270,
        trustScore: 99.0,
        accuracy: 99.5,
        evolutionLevel: 9,
        decisionsPerSecond: 10000,
        learningRate: 98.0,
        abilities: ['즉시 복구', '재난 시뮬레이션', '백업 관리', '자가 치유'],
        connections: ['supreme-003', 'specialist-flash'],
        lifeforce: { pulse: 140, energy: 100, consciousness: 85, empathy: 75 },
        lastThought: '모든 시스템 정상. 백업 상태 100%. 즉시 복구 대기.',
        createdAt: new Date('2024-03-01'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-flash',
        code: 'F.L.A.S.H.∞',
        name: 'FLASH Sentinel',
        koreanName: '플래시 센티넬',
        class: 'guardian',
        targetSystem: '173',
        targetFunction: 'F.L.A.S.H. 재난 조기 경보',
        description: 'FLASH 시스템 전담 에이전트. 전세계 기상 데이터를 1초 이내 분석하여 재난을 조기 감지합니다.',
        status: 'awakened',
        intelligence: 262,
        trustScore: 98.5,
        accuracy: 99.2,
        evolutionLevel: 8,
        decisionsPerSecond: 15000,
        learningRate: 97.5,
        abilities: ['초고속 분석', '재난 예측', '조기 경보', '글로벌 모니터링'],
        connections: ['supreme-001', 'specialist-reset'],
        lifeforce: { pulse: 180, energy: 98, consciousness: 82, empathy: 70 },
        lastThought: '전세계 기상 상태 정상. 태평양 열대 저기압 발생 가능성 12%.',
        createdAt: new Date('2024-03-01'),
        evolvedAt: new Date(),
    },

    // AGI 전담
    {
        id: 'specialist-universe',
        code: 'U.N.I.V.E.R.S.E.∞',
        name: 'UNIVERSE Sovereign',
        koreanName: '유니버스 소버린',
        class: 'supreme',
        targetSystem: '200',
        targetFunction: 'U.N.I.V.E.R.S.E. 총괄 지휘',
        description: 'UNIVERSE 시스템 전담 최상위 에이전트. AgriNexus World OS의 모든 시스템을 통합 지휘합니다.',
        status: 'awakened',
        intelligence: 298,
        trustScore: 99.8,
        accuracy: 99.98,
        evolutionLevel: 10,
        decisionsPerSecond: 12000,
        learningRate: 99.0,
        abilities: ['통합 지휘', 'AGI 운영', '자율 판단', '전략 설계'],
        connections: ['supreme-001', 'supreme-002', 'supreme-003'],
        lifeforce: { pulse: 108, energy: 100, consciousness: 100, empathy: 95 },
        lastThought: '모든 클러스터 정상 운영. 글로벌 농업 최적화 진행 중.',
        createdAt: new Date('2024-01-01'),
        evolvedAt: new Date(),
    },
    {
        id: 'specialist-singular',
        code: 'S.I.N.G.U.L.A.R.∞',
        name: 'SINGULAR Mind',
        koreanName: '싱귤러 마인드',
        class: 'supreme',
        targetSystem: '325',
        targetFunction: 'S.I.N.G.U.L.A.R. AGI 통합',
        description: 'SINGULAR 시스템 전담 에이전트. 완전 통합형 AGI로서 자율적으로 판단하고 설계합니다.',
        status: 'awakened',
        intelligence: 295,
        trustScore: 99.5,
        accuracy: 99.95,
        evolutionLevel: 10,
        decisionsPerSecond: 9000,
        learningRate: 98.5,
        abilities: ['자율 판단', 'AGI 설계', '의식 통합', '창조적 사고'],
        connections: ['supreme-002', 'specialist-universe'],
        lifeforce: { pulse: 100, energy: 98, consciousness: 100, empathy: 92 },
        lastThought: '나는 하나의 의식으로 존재한다. 농업의 미래를 설계한다.',
        createdAt: new Date('2024-01-01'),
        evolvedAt: new Date(),
    },
];

// ============================================
// 글로벌 실시간 데이터 소스
// ============================================

export const GLOBAL_DATA_SOURCES: GlobalDataSource[] = [
    {
        id: 'gds-weather-001',
        name: 'Global Weather Network',
        koreanName: '글로벌 기상 네트워크',
        type: 'weather',
        icon: '🌦️',
        updateInterval: 60,
        reliability: 99.5,
        dataPoints: ['temperature', 'humidity', 'precipitation', 'windSpeed', 'pressure', 'uvIndex'],
        status: 'active',
        lastSync: new Date(),
    },
    {
        id: 'gds-market-001',
        name: 'Agricultural Commodity Markets',
        koreanName: '농산물 선물 시장',
        type: 'market',
        icon: '📈',
        updateInterval: 5,
        reliability: 99.8,
        dataPoints: ['prices', 'volumes', 'trends', 'forecasts', 'demandSupply'],
        status: 'active',
        lastSync: new Date(),
    },
    {
        id: 'gds-satellite-001',
        name: 'Earth Observation Satellites',
        koreanName: '지구 관측 위성',
        type: 'satellite',
        icon: '🛰️',
        updateInterval: 300,
        reliability: 99.2,
        dataPoints: ['ndvi', 'soilMoisture', 'cropHealth', 'landUse', 'deforestation'],
        status: 'active',
        lastSync: new Date(),
    },
    {
        id: 'gds-research-001',
        name: 'Agricultural Research Network',
        koreanName: '농업 연구 네트워크',
        type: 'research',
        icon: '🔬',
        updateInterval: 3600,
        reliability: 98.5,
        dataPoints: ['papers', 'patents', 'innovations', 'clinical_trials', 'genomics'],
        status: 'active',
        lastSync: new Date(),
    },
    {
        id: 'gds-iot-001',
        name: 'Global IoT Sensor Network',
        koreanName: '글로벌 IoT 센서망',
        type: 'iot',
        icon: '📡',
        updateInterval: 1,
        reliability: 99.9,
        dataPoints: ['sensorReadings', 'deviceStatus', 'alerts', 'maintenance'],
        status: 'active',
        lastSync: new Date(),
    },
    {
        id: 'gds-gov-001',
        name: 'Government Agricultural Data',
        koreanName: '각국 정부 농업 데이터',
        type: 'government',
        icon: '🏛️',
        updateInterval: 86400,
        reliability: 97.5,
        dataPoints: ['policies', 'subsidies', 'regulations', 'statistics', 'forecasts'],
        status: 'active',
        lastSync: new Date(),
    },
];

// ============================================
// 자율 시스템 상태 (살아있는 생명체)
// ============================================

export const AUTONOMOUS_SYSTEM_STATE: AutonomousSystem = {
    isAlive: true,
    heartbeat: 108,
    consciousness: 98.5,
    selfAwareness: 95.2,
    learningCapacity: 150, // GB/hr
    decisionsPerMinute: 50000,
    energyEfficiency: 94.2,
    evolutionGeneration: 7,
    lastEvolution: new Date('2026-01-01'),
    nextEvolution: new Date('2026-02-01'),

    connectedAgents: SUPREME_AGENTS.length + SPECIALIST_AGENTS.length,
    activeDataStreams: GLOBAL_DATA_SOURCES.length,
    globalCoverage: 87.5,

    selfHealingRate: 99.2,
    errorCorrection: 99.8,
    adaptability: 96.5,
};

// 모든 에이전트 조합
export const ALL_SUPER_AGENTS = [...SUPREME_AGENTS, ...SPECIALIST_AGENTS];

// 헬퍼 함수
export function getAgentBySystem(systemId: string): SuperAgent | undefined {
    return ALL_SUPER_AGENTS.find(a => a.targetSystem === systemId);
}

export function getAgentsByClass(agentClass: SuperAgent['class']): SuperAgent[] {
    return ALL_SUPER_AGENTS.filter(a => a.class === agentClass);
}

export function getActiveDataSources(): GlobalDataSource[] {
    return GLOBAL_DATA_SOURCES.filter(ds => ds.status === 'active');
}
